### ISSUE TITLE
Matrix Inverse seems incorrect

### ISSUE THREAD

**Issue by scottplantenga** [emehiel/Horizon#41]
In some testing it appears that the matrix inverse is incorrect for the 3x3 matrices I am working with in the last element (row = 3, col = 3). This is found in comparing the result to the inverse found analytically as well as attempting to verify that the inverse multiplied with the original matrix produces the identity matrix (again, it looks OK except for the last element)

**Comment by emehiel** [comment]
Fixed.  The element in the last row was not normalized due to a for loop that did not run to the last row value.
